name: snorya
description: "Wikipedia makalelerini Gemini AI ile özetleyip sunan bir uygulama."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.2.2
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_markdown: ^0.7.7+1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/snorya_icon.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/snorya_icon.png"
  remove_alpha_ios: true
